load coast;
%latlim = [-80 80];
%lonlim = [0 360];
latlim = [-45 40];
lonlim = [-30 65];
axesm('MapProjection','mercator',...
      'MapLatLimit',latlim,'MapLonLimit',lonlim,...
      'MLabelLocation',30,'MLineLocation',10,...
      'PLabelLocation',30,'PLineLocation',10,...
      'LabelFormat','signed');
mlabel; plabel; framem;
plotm(lat,long,'LineWidth',1,'Color','blue');
